# Generated by Django 6.0.1 on 2026-01-20 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название тарифа')),
                ('like', models.IntegerField(default=0, verbose_name='Лайков')),
                ('like_speed', models.IntegerField(default=0, verbose_name='Скорость. Лайков')),
                ('coverage', models.IntegerField(default=0, verbose_name='Охват')),
                ('coverage_speed', models.IntegerField(default=0, verbose_name='Скорость. Охват')),
                ('saved', models.IntegerField(default=0, verbose_name='Сохраненные')),
                ('saved_speed', models.IntegerField(default=0, verbose_name='Скорость. Сохраненные')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('views_2', models.IntegerField(default=0, verbose_name='Просмотров 2')),
                ('views_2_speed', models.IntegerField(default=0, verbose_name='Скорость. Просмотров 2')),
                ('jap_quantity', models.IntegerField(default=0, verbose_name='Quantity JAP')),
                ('jap_runs', models.IntegerField(default=0, verbose_name='Runs JAP')),
                ('jap_interval', models.IntegerField(default=0, verbose_name='Interval (in minutes) JAP')),
                ('repost', models.IntegerField(default=0, verbose_name='Репост')),
                ('repost_speed', models.IntegerField(default=0, verbose_name='Скорость. Репост')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TarifCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(max_length=20, verbose_name='Лайков')),
                ('coverage', models.CharField(max_length=20, verbose_name='Охват')),
                ('views', models.CharField(max_length=20, verbose_name='Просмотров')),
                ('views_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Просмотров 2')),
                ('saved', models.CharField(max_length=20, verbose_name='Сохраненные')),
                ('repost', models.CharField(max_length=20, verbose_name='Репост')),
                ('jap_views1', models.CharField(max_length=20, verbose_name='Просмотров JAP 1')),
                ('jap_views2', models.CharField(max_length=20, verbose_name='Просмотров JAP 2')),
            ],
            options={
                'verbose_name': 'Тариф код',
                'verbose_name_plural': 'Тариф код',
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(verbose_name='venro.ru')),
                ('jap_key', models.TextField(blank=True, null=True, verbose_name='justanotherpanel.com')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'API-ключ',
                'verbose_name_plural': 'API-ключи',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата платежа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('tarif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tarif', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('orders', models.TextField(blank=True, null=True)),
                ('jap_orders', models.TextField(blank=True, null=True)),
                ('for_test', models.BooleanField(default=False)),
                ('publication', models.IntegerField(default=0, verbose_name='Публикаций')),
                ('finished', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tarif')),
            ],
        ),
    ]
