# Generated by Django 3.2.9 on 2024-08-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240817_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телеграм ID'),
        ),
    ]
