# Generated by Django 3.2.9 on 2024-08-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240817_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='client',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Инстаграм'),
        ),
    ]
