# Generated by Django 3.2.9 on 2024-08-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20240817_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='instagram',
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
