# Generated by Django 3.2.9 on 2024-08-17 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20240817_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tarif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tarif', verbose_name='Тариф'),
        ),
    ]
