# Generated by Django 3.2.9 on 2025-02-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_client_tarif'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='coverage',
            field=models.IntegerField(default=0, verbose_name='Охват'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Лайков'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='publication',
            field=models.IntegerField(default=0, verbose_name='Публикаций'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='saved',
            field=models.IntegerField(default=0, verbose_name='Сохраненные'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
    ]
