# Generated by Django 5.1 on 2025-02-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='publication',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
