# Generated by Django 5.1 on 2025-03-04 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_apikey_options_remove_order_charge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarif',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='views',
        ),
        migrations.AddField(
            model_name='apikey',
            name='jap_key',
            field=models.TextField(blank=True, null=True, verbose_name='justanotherpanel.com'),
        ),
        migrations.AddField(
            model_name='order',
            name='jap_orders',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='publication',
            field=models.IntegerField(default=0, verbose_name='Публикаций'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.TextField(verbose_name='venro.ru'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
