# Generated by Django 5.1 on 2025-03-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_tarif_publication_remove_tarif_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
    ]
