# Generated by Django 5.1 on 2025-03-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_tarif_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='repost',
            field=models.IntegerField(default=0, verbose_name='Репост'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='repost_speed',
            field=models.IntegerField(default=0, verbose_name='Скорость. Репост'),
        ),
    ]
