# Generated by Django 5.1 on 2025-03-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_tarif_repost_tarif_repost_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='jap_interval',
            field=models.IntegerField(default=0, verbose_name='Interval (in minutes) JAP'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='jap_quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity JAP'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='jap_runs',
            field=models.IntegerField(default=0, verbose_name='Runs JAP'),
        ),
    ]
