# Generated by Django 5.1 on 2025-04-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_tarif_jap_interval_tarif_jap_quantity_tarif_jap_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
