# Generated by Django 3.2.9 on 2025-10-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(max_length=20, verbose_name='Лайков')),
                ('coverage', models.CharField(max_length=20, verbose_name='Охват')),
                ('views', models.CharField(max_length=20, verbose_name='Просмотров')),
                ('saved', models.CharField(max_length=20, verbose_name='Сохраненные')),
                ('repost', models.CharField(max_length=20, verbose_name='Репост')),
                ('jap_views1', models.CharField(max_length=20, verbose_name='Просмотров JAP 1')),
                ('jap_views2', models.CharField(max_length=20, verbose_name='Просмотров JAP 2')),
            ],
            options={
                'verbose_name': 'Тариф код',
                'verbose_name_plural': 'Тариф код',
            },
        ),
    ]
