# Generated by Django 5.1 on 2026-01-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_tarifcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='views_2',
            field=models.IntegerField(default=0, verbose_name='Просмотров 2'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='views_2_speed',
            field=models.IntegerField(default=0, verbose_name='Скорость. Просмотров 2'),
        ),
        migrations.AddField(
            model_name='tarifcodes',
            name='views_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Просмотров 2'),
        ),
    ]
